### ISSUE TITLE
Ticker library

### ISSUE THREAD

**Issue by mariusrugan** [vitzaoral/esp32-beehive-wifi-2#1]
Hi,

I'm trying to setup my development environment for this and for the first version and Ticker library is included from esp32 

  Ticker.h - esp32 library that calls functions periodically
  Copyright (c) 2017 Bert Melis. All rights reserved.

which has completely different API than the one you're using. 
example:

```
src/main.cpp:34:27: error: 'class Ticker' has no member named 'start'
   timerSendDataToInternet.start();
```

Can you please clarify what lib is used ?

Thanks for your work, i'm trying to achieve the same, a beehive monitoring system on a esp32-cam board. Can't say i'm esp32/C++ expert so please bare with me. :)

**Comment by vitzaoral** [comment]
Hi mariusrugan, it seems you have different version of Ticker library. It's true that there are many tickers library and it's little bit confusing (my bad). I am using library from [Stefan Staub](https://github.com/sstaub/Ticker). If you are using Visual Studio Code and Platformio, you can easily find this library and install it.

I am working on this project almost every day, so I will post some other updates in next days and weeks...spring is coming 🐝 :)

Good luck with your project :)
